# Generated by Django 5.0.6 on 2024-06-25 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snipet', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='What_our_Client_says',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='What_our_Client_says/')),
                ('comment', models.TextField()),
            ],
        ),
    ]
