# Generated by Django 5.0.6 on 2024-06-25 18:49

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snipet', '0002_what_our_client_says'),
    ]

    operations = [
        migrations.CreateModel(
            name='About_us_page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='About_us/')),
                ('content', ckeditor.fields.RichTextField()),
            ],
        ),
    ]
