# Generated by Django 5.0.6 on 2024-07-07 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snipet', '0003_about_us_page'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDetailsForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('gif', models.FileField(blank=True, null=True, upload_to='UserDetailsForm/')),
            ],
        ),
    ]
