# Generated by Django 5.0.6 on 2024-07-09 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snipet', '0005_workoutpge'),
    ]

    operations = [
        migrations.AddField(
            model_name='home_hero_section_images',
            name='mobile_image',
            field=models.ImageField(blank=True, null=True, upload_to='Home_hero_section_Images/'),
        ),
    ]
