# Generated by Django 5.0.6 on 2024-07-09 23:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snipet', '0006_home_hero_section_images_mobile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='home_hero_section_images',
            name='mobile_image',
        ),
    ]
