# Generated by Django 5.0.6 on 2024-08-07 15:53

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snipet', '0007_remove_home_hero_section_images_mobile_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nutations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(blank=True, null=True, upload_to='Post/')),
                ('content', ckeditor.fields.RichTextField()),
                ('date_posted', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
