# Generated by Django 5.0.6 on 2024-06-18 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0005_affiliate_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Why_Choose_Us_Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('video', models.FileField(blank=True, null=True, upload_to='Why_Choose_Us_Video/')),
            ],
        ),
    ]
