# Generated by Django 5.0.6 on 2024-06-18 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0008_home_hero_section_images'),
    ]

    operations = [
        migrations.CreateModel(
            name='Home_how_it_work_Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='Home_hero_section_Images/')),
            ],
        ),
    ]
