# Generated by Django 5.0.6 on 2024-06-19 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0009_home_how_it_work_images'),
    ]

    operations = [
        migrations.CreateModel(
            name='Home_What_Our_Clients_Say_About_Us',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=1200)),
            ],
        ),
    ]
