# Generated by Django 5.0.6 on 2024-06-19 15:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0010_home_what_our_clients_say_about_us'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gym_Pakage_elements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pointer', models.CharField(max_length=255, null=True)),
                ('gym_package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gym.gympackage')),
            ],
        ),
    ]
