# Generated by Django 5.0.6 on 2024-06-19 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0013_post_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255)),
                ('answer', models.TextField()),
            ],
        ),
    ]
