# Generated by Django 5.0.6 on 2024-06-19 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0015_remove_order_order_date_remove_order_user_order_bmi_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
