# Generated by Django 5.0.6 on 2024-06-20 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0017_order_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='person_image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
