# Generated by Django 5.0.6 on 2024-06-20 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0018_order_person_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='age',
            field=models.IntegerField(null=True),
        ),
    ]
