# Generated by Django 5.0.6 on 2024-06-20 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0019_order_age'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
