# Generated by Django 5.0.6 on 2024-06-21 15:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0021_userprofile_workoutplan'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('height_ft', models.IntegerField()),
                ('height_in', models.IntegerField()),
                ('weight_kg', models.FloatField()),
                ('age', models.IntegerField()),
                ('bmi', models.FloatField()),
                ('person_image', models.ImageField(blank=True, null=True, upload_to='person_images/')),
                ('tools_image', models.ImageField(blank=True, null=True, upload_to='tools_images/')),
                ('score', models.IntegerField()),
                ('practice_schedule', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
