# Generated by Django 5.0.6 on 2024-06-21 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0022_userassessment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userassessment',
            name='bmi',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
