# Generated by Django 5.0.6 on 2024-06-21 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0023_alter_userassessment_bmi'),
    ]

    operations = [
        migrations.AddField(
            model_name='userassessment',
            name='goal',
            field=models.CharField(blank=True, choices=[('Gain Weight', 'Gain Weight'), ('Lose Weight', 'Lose Weight')], max_length=100, null=True),
        ),
    ]
