# Generated by Django 5.0.6 on 2024-06-21 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0024_userassessment_goal'),
    ]

    operations = [
        migrations.AddField(
            model_name='userassessment',
            name='training_days_per_week',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userassessment',
            name='workout_preferences',
            field=models.CharField(blank=True, choices=[('Cardio', 'Cardio'), ('Strength Training', 'Strength Training'), ('Flexibility', 'Flexibility'), ('Mixed', 'Mixed')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userassessment',
            name='practice_schedule',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userassessment',
            name='score',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
