# Generated by Django 5.0.6 on 2024-06-21 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0026_workoutschedule_workoutscheduleday'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workoutscheduleday',
            name='workout',
        ),
        migrations.DeleteModel(
            name='WorkoutSchedule',
        ),
        migrations.DeleteModel(
            name='WorkoutScheduleDay',
        ),
    ]
