# Generated by Django 5.0.6 on 2024-06-21 18:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0027_remove_workoutscheduleday_workout_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkoutSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user_assessment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='gym.userassessment')),
            ],
        ),
        migrations.CreateModel(
            name='WorkoutScheduleDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('workout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gym.workoutschedule')),
            ],
        ),
    ]
