# Generated by Django 5.0.6 on 2024-06-21 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0028_workoutschedule_workoutscheduleday'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='age',
        ),
        migrations.RemoveField(
            model_name='order',
            name='bmi',
        ),
        migrations.RemoveField(
            model_name='order',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='order',
            name='height_ft',
        ),
        migrations.RemoveField(
            model_name='order',
            name='height_in',
        ),
        migrations.RemoveField(
            model_name='order',
            name='image',
        ),
        migrations.RemoveField(
            model_name='order',
            name='person_image',
        ),
        migrations.RemoveField(
            model_name='order',
            name='weight_kg',
        ),
    ]
