# Generated by Django 5.0.6 on 2024-06-21 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0029_remove_order_age_remove_order_bmi_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
