# Generated by Django 5.0.6 on 2024-06-23 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0031_workoutschedule_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='workoutscheduleday',
            name='day_number',
            field=models.CharField(blank=True, max_length=480, null=True),
        ),
    ]
