# Generated by Django 5.0.6 on 2024-06-23 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0032_workoutscheduleday_day_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='workoutscheduleday',
            name='sent_to_user',
            field=models.BooleanField(default=False),
        ),
    ]
