# Generated by Django 5.0.6 on 2024-06-23 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0033_workoutscheduleday_sent_to_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='userassessment',
            name='whatsapp',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
