# Generated by Django 5.0.6 on 2024-06-23 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0034_userassessment_whatsapp'),
    ]

    operations = [
        migrations.AddField(
            model_name='affiliate',
            name='customer_comission',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='affiliate',
            name='his_comission',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='cupon_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
