# Generated by Django 5.0.6 on 2024-06-23 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0035_affiliate_customer_comission_affiliate_his_comission_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='affiliate',
            name='total_clicks',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
