# Generated by Django 5.0.6 on 2024-06-23 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0036_affiliate_total_clicks'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FAQ',
        ),
        migrations.DeleteModel(
            name='Home_hero_section_Images',
        ),
        migrations.DeleteModel(
            name='Home_how_it_work_Images',
        ),
        migrations.DeleteModel(
            name='Home_What_Our_Clients_Say_About_Us',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
        migrations.DeleteModel(
            name='Why_Choose_Us_Images',
        ),
        migrations.DeleteModel(
            name='Why_Choose_Us_Video',
        ),
    ]
