# Generated by Django 5.0.6 on 2024-06-23 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0037_delete_faq_delete_home_hero_section_images_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='price',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
