# Generated by Django 5.0.6 on 2024-06-23 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0038_order_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='affiliate',
            name='total_clicks',
            field=models.CharField(blank=True, default='0', max_length=255, null=True),
        ),
    ]
