# Generated by Django 5.0.6 on 2024-06-23 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0039_alter_affiliate_total_clicks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='affiliate',
            name='total_clicks',
            field=models.IntegerField(blank=True, default=0, max_length=255, null=True),
        ),
    ]
