# Generated by Django 5.0.6 on 2024-06-23 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0040_alter_affiliate_total_clicks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='affiliate',
            name='total_amunt',
            field=models.CharField(default=0, max_length=200),
        ),
    ]
