# Generated by Django 5.0.6 on 2024-06-23 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0041_alter_affiliate_total_amunt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='affiliate',
            name='total_amunt',
            field=models.CharField(default='0', max_length=200),
        ),
        migrations.AlterField(
            model_name='affiliate',
            name='total_clicks',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
