# Generated by Django 5.0.6 on 2024-06-24 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0042_alter_affiliate_total_amunt_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='affiliate',
            name='total_amunt',
            field=models.IntegerField(default='0'),
        ),
    ]
