# Generated by Django 5.0.6 on 2024-06-24 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0043_alter_affiliate_total_amunt'),
    ]

    operations = [
        migrations.AddField(
            model_name='userassessment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
