# Generated by Django 5.0.6 on 2024-07-03 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0045_alter_order_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='userassessment',
            name='target_body_part',
            field=models.CharField(blank=True, choices=[('Upperbody Body', 'Upperbody Body'), ('Lower Body', 'Lower Body'), ('Upperbody and Lower Body', 'Upperbody and Lower Body')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userassessment',
            name='target_musclemuscle',
            field=models.CharField(blank=True, choices=[('Muscle Gain', 'Muscle Gain'), ('Muscle Lose', 'Muscle Lose')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userassessment',
            name='target_weight',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userassessment',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=100),
        ),
    ]
