# Generated by Django 5.0.6 on 2024-07-03 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0046_userassessment_target_body_part_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userassessment',
            old_name='target_musclemuscle',
            new_name='target_muscle',
        ),
    ]
