# Generated by Django 5.0.6 on 2024-07-03 22:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0047_rename_target_musclemuscle_userassessment_target_muscle'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAssessmentHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height_ft', models.IntegerField()),
                ('height_in', models.IntegerField()),
                ('weight_kg', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user_assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gym.userassessment')),
            ],
        ),
    ]
