# Generated by Django 5.0.6 on 2024-07-04 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0049_alter_workoutscheduleday_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workoutscheduleday',
            name='day',
            field=models.JSONField(null=True),
        ),
    ]
