# Generated by Django 5.0.6 on 2024-07-04 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0050_alter_workoutscheduleday_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userassessment',
            name='person_image',
            field=models.ImageField(blank=True, max_length=840, null=True, upload_to='person_images/'),
        ),
        migrations.AlterField(
            model_name='userassessment',
            name='tools_image',
            field=models.ImageField(blank=True, max_length=840, null=True, upload_to='tools_images/'),
        ),
    ]
