# Generated by Django 5.0.6 on 2024-07-06 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0051_alter_userassessment_person_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('equipment', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='exercises/')),
                ('target', models.CharField(max_length=255)),
                ('instructions', models.TextField()),
            ],
        ),
    ]
