# Generated by Django 5.0.6 on 2024-07-08 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0052_exercise'),
    ]

    operations = [
        migrations.AddField(
            model_name='workoutscheduleday',
            name='user_completed',
            field=models.BooleanField(default=False),
        ),
    ]
