# Generated by Django 5.0.6 on 2024-07-09 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0053_workoutscheduleday_user_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='workoutscheduleday',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
