# Generated by Django 5.0.6 on 2024-07-09 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0055_userworkouttaken'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workoutscheduleday',
            name='user_completed',
        ),
    ]
