# Generated by Django 5.0.6 on 2024-07-09 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0056_remove_workoutscheduleday_user_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='userworkouttaken',
            name='calorys',
            field=models.CharField(blank=True, max_length=480, null=True),
        ),
    ]
