# Generated by Django 5.0.6 on 2024-07-09 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0057_userworkouttaken_calorys'),
    ]

    operations = [
        migrations.AddField(
            model_name='userworkouttaken',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
