# Generated by Django 5.0.6 on 2024-08-08 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0060_gym_coach_alter_conversation_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gym_coach',
            name='image',
            field=models.ImageField(null=True, upload_to='coach/'),
        ),
    ]
