# Generated by Django 5.0.6 on 2024-08-08 17:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0061_gym_coach_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='userassessment',
            name='coach',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gym.gym_coach'),
        ),
    ]
