# Generated by Django 5.0.6 on 2024-08-10 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0062_userassessment_coach'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userassessment',
            name='age',
        ),
        migrations.RemoveField(
            model_name='userassessment',
            name='bmi',
        ),
        migrations.RemoveField(
            model_name='userassessment',
            name='goal',
        ),
        migrations.RemoveField(
            model_name='userassessment',
            name='height_ft',
        ),
        migrations.RemoveField(
            model_name='userassessment',
            name='height_in',
        ),
        migrations.RemoveField(
            model_name='userassessment',
            name='person_image',
        ),
        migrations.RemoveField(
            model_name='userassessment',
            name='practice_schedule',
        ),
        migrations.RemoveField(
            model_name='userassessment',
            name='score',
        ),
        migrations.RemoveField(
            model_name='userassessment',
            name='target_body_part',
        ),
        migrations.RemoveField(
            model_name='userassessment',
            name='target_muscle',
        ),
        migrations.RemoveField(
            model_name='userassessment',
            name='target_weight',
        ),
        migrations.RemoveField(
            model_name='userassessment',
            name='tools_image',
        ),
        migrations.RemoveField(
            model_name='userassessment',
            name='training_days_per_week',
        ),
        migrations.RemoveField(
            model_name='userassessment',
            name='weight_kg',
        ),
        migrations.RemoveField(
            model_name='userassessment',
            name='whatsapp',
        ),
        migrations.RemoveField(
            model_name='userassessment',
            name='workout_preferences',
        ),
        migrations.AddField(
            model_name='userassessment',
            name='equipment',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userassessment',
            name='fit',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userassessment',
            name='height',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='userassessment',
            name='practice_location',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='userassessment',
            name='schedule',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='userassessment',
            name='target_area',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userassessment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='userassessment',
            name='weight',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='userassessment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='userassessment',
            name='gender',
            field=models.CharField(choices=[('man', 'Man'), ('woman', 'Woman')], max_length=10),
        ),
    ]
