# Generated by Django 5.0.6 on 2024-08-10 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0063_remove_userassessment_age_remove_userassessment_bmi_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userassessment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='userassessment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
