# Generated by Django 5.0.6 on 2024-08-10 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0068_remove_message_sender_conversation_room_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='conversation',
        ),
        migrations.RemoveField(
            model_name='message',
            name='content_type',
        ),
        migrations.DeleteModel(
            name='Conversation',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
    ]
