# Generated by Django 5.0.6 on 2024-08-12 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0071_alter_userassessment_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='equipment_list',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='equipment/')),
            ],
        ),
    ]
