# Generated by Django 5.0.6 on 2024-08-14 13:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0072_equipment_list'),
    ]

    operations = [
        migrations.CreateModel(
            name='NutritionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('calories', models.IntegerField()),
                ('protein', models.CharField(max_length=50)),
                ('carbs', models.CharField(max_length=50)),
                ('fat', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('items', models.ManyToManyField(to='gym.nutritionitem')),
            ],
        ),
        migrations.CreateModel(
            name='NutritionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('total_calories', models.IntegerField()),
                ('total_protein', models.CharField(max_length=50)),
                ('total_carbs', models.CharField(max_length=50)),
                ('total_fat', models.CharField(max_length=50)),
                ('breakfast', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='breakfast', to='gym.meal')),
                ('dinner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dinner', to='gym.meal')),
                ('lunch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lunch', to='gym.meal')),
                ('snack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snack', to='gym.meal')),
            ],
        ),
    ]
