# Generated by Django 5.0.6 on 2024-10-14 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0073_nutritionitem_meal_nutritionplan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nutritionitem',
            name='carbs',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='nutritionitem',
            name='fat',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='nutritionitem',
            name='protein',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='nutritionplan',
            name='total_carbs',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='nutritionplan',
            name='total_fat',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='nutritionplan',
            name='total_protein',
            field=models.IntegerField(),
        ),
    ]
