# Generated by Django 5.0.6 on 2024-10-14 14:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0074_alter_nutritionitem_carbs_alter_nutritionitem_fat_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nutritionplan',
            old_name='date',
            new_name='created_at',
        ),
        migrations.AddField(
            model_name='nutritionplan',
            name='day_number',
            field=models.CharField(blank=True, max_length=480, null=True),
        ),
        migrations.AddField(
            model_name='nutritionplan',
            name='user_assessment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gym.userassessment'),
        ),
    ]
