# Generated by Django 5.0.6 on 2024-10-14 15:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0075_rename_date_nutritionplan_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='user_assessment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gym.userassessment'),
        ),
        migrations.AddField(
            model_name='nutritionitem',
            name='user_assessment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gym.userassessment'),
        ),
    ]
