# Generated by Django 5.0.6 on 2024-10-14 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0076_meal_user_assessment_nutritionitem_user_assessment'),
    ]

    operations = [
        migrations.AddField(
            model_name='nutritionitem',
            name='image_url',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
