# Generated by Django 5.0.6 on 2024-10-14 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0077_nutritionitem_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='role',
            field=models.CharField(default='coach', max_length=50),
        ),
    ]
