# Generated by Django 5.0.6 on 2024-10-14 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0078_conversation_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='role',
            field=models.CharField(default='user', max_length=50),
        ),
    ]
