# Generated by Django 5.0.6 on 2024-10-14 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0079_alter_conversation_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quotes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote', models.CharField(max_length=255)),
            ],
        ),
    ]
