# Generated by Django 5.0.6 on 2024-10-14 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0080_quotes'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotes',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
