# Generated by Django 5.0.6 on 2024-10-15 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0081_quotes_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='gympackage',
            name='price_id',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
