# Generated by Django 5.0.6 on 2024-10-16 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0085_alter_token_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversation',
            name='role',
        ),
    ]
