# Generated by Django 5.0.6 on 2024-10-16 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0086_remove_conversation_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Token_package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('stripe_name', models.CharField(max_length=255)),
            ],
        ),
    ]
