# Generated by Django 5.0.6 on 2024-10-16 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0087_token_package'),
    ]

    operations = [
        migrations.AddField(
            model_name='token_package',
            name='price',
            field=models.IntegerField(null=True),
        ),
    ]
