# Generated by Django 5.0.6 on 2024-10-16 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0088_token_package_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='token_package',
            old_name='name',
            new_name='quantity',
        ),
    ]
