# Generated by Django 5.0.6 on 2024-10-16 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0089_rename_name_token_package_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token_package',
            name='quantity',
            field=models.IntegerField(max_length=255),
        ),
    ]
