# Generated by Django 5.0.6 on 2024-06-23 20:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AutoLinkMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent_message', models.CharField(max_length=800, null=True, unique=True)),
                ('title', models.CharField(help_text='title of the card', max_length=800)),
                ('subtitle', models.CharField(help_text='Subtitle of the card', max_length=800, null=True)),
                ('imegs', models.ImageField(help_text='image for the card', upload_to='static/images')),
                ('link', models.CharField(default='https://snapafit.com/', help_text='Enter Target Page Link Here To Redirect', max_length=800, null=True)),
                ('button_link', models.CharField(default='https://snapafit.com/', help_text='Enter Target Page Link Here To Redirect. this can be diffrent from the above link.', max_length=800, null=True)),
                ('button_name', models.CharField(default='Visit Now', help_text='Button show this text on it', max_length=800, null=True)),
            ],
            options={
                'verbose_name': 'Automated Message Link & Image Answers',
                'verbose_name_plural': 'Automated Message Link & Image Answers',
            },
        ),
        migrations.CreateModel(
            name='AutoMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent_message', models.CharField(max_length=800, null=True, unique=True)),
                ('answer', models.TextField()),
            ],
            options={
                'verbose_name': 'Automated Messages',
                'verbose_name_plural': 'Automated Messages',
            },
        ),
        migrations.CreateModel(
            name='ButtonLinkMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent_message', models.CharField(max_length=800, null=True, unique=True)),
                ('text', models.CharField(help_text='title of the card', max_length=800)),
                ('button_link', models.CharField(default='https://snapafit.com/', help_text='Enter Target Page Link Here To Redirect. this can be diffrent from the above link.', max_length=800, null=True)),
                ('button_name', models.CharField(default='Visit Now', help_text='Button show this text on it', max_length=800, null=True)),
            ],
            options={
                'verbose_name': 'Automated Button Message Link Questions',
                'verbose_name_plural': 'Automated Button Message Link Questions',
            },
        ),
        migrations.CreateModel(
            name='Extra_quick_replays',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=800, null=True, unique=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Automated Extra quicks replays',
                'verbose_name_plural': 'Automated Extra quicks replays',
            },
        ),
        migrations.CreateModel(
            name='AutoLinkMessageQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=800, null=True, unique=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('q_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='chatbot.autolinkmessage')),
            ],
            options={
                'verbose_name': 'Automated Message Link Questions',
                'verbose_name_plural': 'Automated Message Link Questions',
            },
        ),
        migrations.CreateModel(
            name='AutoMessageQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('q_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='chatbot.automessage')),
            ],
            options={
                'verbose_name': 'Automated Message Questions',
                'verbose_name_plural': 'Automated Message Questions',
            },
        ),
        migrations.CreateModel(
            name='AdditionalBtnLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('button_link', models.CharField(default='https://snapafit.com/', help_text='Enter Target Page Link Here To Redirect. this can be diffrent from the above link.', max_length=800, null=True)),
                ('button_name', models.CharField(default='Visit Now', help_text='Button show this text on it', max_length=800, null=True)),
                ('q_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='chatbot.buttonlinkmessage')),
            ],
            options={
                'verbose_name': 'Automated Button Message Link Answers',
                'verbose_name_plural': 'Automated Button Message Link Answers',
            },
        ),
        migrations.CreateModel(
            name='ButtonLinkMessageQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=800, null=True, unique=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('q_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='chatbot.buttonlinkmessage')),
            ],
            options={
                'verbose_name': 'Automated Button Message Link Questions',
                'verbose_name_plural': 'Automated Button Message Link Questions',
            },
        ),
        migrations.CreateModel(
            name='FacebookUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fb_id', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('language', models.CharField(blank=True, max_length=10, null=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
