# Generated by Django 5.0.6 on 2024-06-13 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0003_alter_gympackage_discount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gympackage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='gym_packages/'),
        ),
    ]
